name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: vladislavkovaliov/wi-github-actions/.github/actions/env-setup@main
        with:
          package-json-path: ./package.json
          package-manager: npm

      - name: Type check
        run: npm run typecheck

      - name: Build
        run: npm run build
